name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.rs'
      - '**/*.py'
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          
      - name: Fix file paths
        run: |
          sed -i 's/docs\\sec.json/docs\/sec.json/g' src/upload_handler.py
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pdoc3
          pip install google-api-python-client
          pip install oauth2client
          pip install httplib2
          pip install moviepy
          pip install kokoro
          pip install torch
          pip install soundfile
          pip install imageio-ffmpeg
          
      - name: Generate Rust Docs
        run: |
          cargo doc --no-deps
          
      - name: Generate Python Docs
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pdoc --html src/ --output-dir ./target/doc/python --force
          
      - name: Combine Docs
        run: |
          mkdir -p ./target/doc/combined
          cp -r ./target/doc/* ./target/doc/combined/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc/combined
